yaml
Copy code
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Deploy to AWS EC2
      env:
        SSH_node.jskeypair17-24.pem_: ${{ secrets.node.jskeypair17-24.pem }}
        HOST: ${{ secrets.node.jskeypair17-24.pem }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$SSH_node.jskeypair17-24.pem_" > node.jskeypair17-24.pem
        chmod 600 private_key.pem
        scp -i node.jskeypair17-24.pem -o StrictHostKeyChecking=no -r . $ubuntu@ec2-13-126-128-210.ap-south-1.compute.amazonaws.com:/path/to/your/app
        ssh -i node.jskeypair17-24.pem -o StrictHostKeyChecking=no $ubuntu@ec2-13-126-128-210.ap-south-1.compute.amazonaws.com "cd /path/to/your/app && npm install && pm2 restart all"
